### ISSUE TITLE
Clone control form accepts invalid users

### ISSUE THREAD

**Issue by juangpc** [brainstorm-tools/bst-java#8]
Hello, 

I've found some behavior worth reporting, with the check-user posting to neuroimage server. I think it is the server that is not working properly, however, I'm not sure, it can also be the java method probe from CloneControl. I've tried with postman to replicate the posting with the server and all I got as an answer was '0'. Either with correct user/pass or with incorrect user and/or pass the response from the server seems to be '0'. 

The exception in the following code is thrown and the method returns a zero. No matter what you insert in the form, you always can continue with the use of BS. The following "Email or username" works. 

![image](https://user-images.githubusercontent.com/8955424/92041003-07ed4680-ed3d-11ea-855f-6227c154ffe1.png)

https://github.com/brainstorm-tools/bst-java/blob/71e565f6b2631b7f4bd28598d1ea841644054196/brainstorm/src/org/brainstorm/dialogs/CloneControl.java#L45

As usual @ftadel, @tmedani, please do comment/delete this issue at your convenience.

Take care,

**Comment by ftadel** [comment]
I modified the code so that it uses newer functions in Matlab instead of the Java code:
https://github.com/brainstorm-tools/brainstorm3/commit/3d2c0c817f9c32c4bd9c6ccb78d9c6256adbd63b

But it doesn't solve the problem. 
Indeed, the login script on the server fails and always returns 1 to any pair or login/password... 
We'll try to fix this. Thanks for reporting.

**Comment by justiniggy** [comment]
I update the PHP file in brainstorm server side to add auth information in headers rather than in parameters. Could you try again and let me know the result?

**Comment by ftadel** [comment]
It seems to be working now.
Thanks!
