### ISSUE TITLE
unzip zip file containing protocol

### ISSUE THREAD

**Issue by juangpc** [brainstorm-tools/bst-java#9]
Hi,

I'm having trouble unzipping a file containing a valid bst tutorial.

Context: 
- In the tutorial: https://neuroimage.usc.edu/brainstorm/Tutorials/ReviewForward, you can download a zipped folder containing a protocol. See the second link at: https://neuroimage.usc.edu/brainstorm/Tutorials/ReviewForward#Data_for_the_spherical_head_model

- Importing this protocol 
This might not be an issue. In other words, I'm not sure if I'm the issue or there is something wrong with the unzip method of in org.brainstorm.file.Unpack.unzip.

https://github.com/brainstorm-tools/bst-java/blob/71e565f6b2631b7f4bd28598d1ea841644054196/brainstorm/src/org/brainstorm/file/Unpack.java#L47

This is called from

https://github.com/brainstorm-tools/brainstorm3/blob/0b5a29f4915edd683642792f1ff1a010df273480/toolbox/io/import_protocol.m#L75

You get the following error: 

![image](https://user-images.githubusercontent.com/8955424/93292086-4d345e00-f7aa-11ea-9fc3-ad047962d14f.png)

After several tests, the bottom line is that if you create the zip file with any method other than exporting a protocol as a zip file (using export_protocol.m within bst), the unzipping might fail. However, if I use "unzip" (introduced in matlab since 2006a) it works just fine. So, I guess, a question would be, why do we invoke java for this?

Thanks,

**Comment by martcous** [comment]
Nice catch, Juan. I had a quick look at our custom unzip() function through a debugger and the issue is that it assumes that files are encountered first in the ZIP input stream, before folders, which is evidently not a correct assumption as the function crashes on ZIP files created outside of Brainstorm like you said. I'm assuming our custom zip() function creates ZIP files in the expected order.

I'm not sure why we are using a custom Java function for this though since zipping & unzipping has been supported in Matlab for so long. There must have been some historical reason to do so, I'll let François chip in. It seems like the best solution rather than supporting our own custom IO functions.

**Comment by ftadel** [comment]
Old implementations of Matlab's unzip were not working correctly on all the OS. 
But I guess this has been fixed for a long time...

Are you happy with this?
https://github.com/brainstorm-tools/brainstorm3/commit/950092061c723854d72f654a21322713642be5d0

**Comment by juangpc** [comment]
Yes I am.
